name: Build & Push

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0' ]
        image: [ cli, fpm, scheduler ]

    name: ${{ matrix.php }}-${{ matrix.image }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.php }}/${{ matrix.image }}
          file: ${{ matrix.php }}/${{ matrix.image }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: misterio92/laravel:${{ matrix.php }}-${{ matrix.image }}

  nginx:
    runs-on: ubuntu-latest

    name: nginx

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: nginx
          file: nginx/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: misterio92/laravel:nginx
